export const EMBEDS = [
  {
    name: "The Community Showcase",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1119749089&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-community-showcase" title="The Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Community Showcase</a></div>',
  },
  {
    name: "The Weekly Showcase Vol.10",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1111382215&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-vol10" title="The Weekly Showcase Vol.10" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase Vol.10</a></div>',
  },
  {
    name: "The Weekly Showcase Vol.9",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1103159263&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-vol9" title="The Weekly Showcase Vol.9" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase Vol.9</a></div>',
  },
  {
    name: "The Weekly Showcase Vol.8.5",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1094612554&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-vol85" title="The Weekly Showcase Vol.8.5" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase Vol.8.5</a></div>',
  },
  {
    name: "The Weekly Showcase Vol. 8",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1090487935&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-vol-8" title="The Weekly Showcase Vol. 8" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase Vol. 8</a></div>',
  },
  {
    name: "The Weekly Showcase Vol.7",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1090502704&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-vol7" title="The Weekly Showcase Vol.7" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase Vol.7</a></div>',
  },
  {
    name: "The Weekly Showcase Vol.6",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1090500037&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-vol6" title="The Weekly Showcase Vol.6" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase Vol.6</a></div>',
  },
  {
    name: "The Weekly Showcase - Volume 5",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1090486102&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-volume-5" title="The Weekly Showcase - Volume 5" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase - Volume 5</a></div>',
  },
  {
    name: "The Weekly Showcase - Volume 4.5",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1068267172&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-volume-45" title="The Weekly Showcase - Volume 4.5" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase - Volume 4.5</a></div>',
  },
  {
    name: "The Weekly Showcase - Volume 4",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1064064679&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-volume-4" title="The Weekly Showcase - Volume 4" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase - Volume 4</a></div>',
  },
  {
    name: "The Weekly Showcase - Volume 3.5",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1037424526&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-volume-35" title="The Weekly Showcase - Volume 3.5" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase - Volume 3.5</a></div>',
  },
  {
    name: "The Weekly Showcase - Volume 3",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1032870577&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-volume-3" title="The Weekly Showcase - Volume 3" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase - Volume 3</a></div>',
  },
  {
    name: "The Weekly Showcase - Volume 2.5",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1028200513&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/the-weekly-showcase-volume-25" title="The Weekly Showcase - Volume 2.5" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase - Volume 2.5</a></div>',
  },
  {
    name: "The Weekly Showcase - Volume Two",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1022988307&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/twc2" title="The Weekly Showcase - Volume Two" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase - Volume Two</a></div>',
  },
  {
    name: "The Weekly Showcase - Volume One",
    embed:
      '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1018288570&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/communityshowcase" title="The Chillhop Community Showcase" target="_blank" style="color: #cccccc; text-decoration: none;">The Chillhop Community Showcase</a> · <a href="https://soundcloud.com/communityshowcase/twc1" title="The Weekly Showcase - Volume One" target="_blank" style="color: #cccccc; text-decoration: none;">The Weekly Showcase - Volume One</a></div>',
  },
];
